// check_ffi.js
// Checks that ble_ffi.json (written by hand) matches ble_bridge.h.
// Run by CMake on every build, so a mismatch fails the build (and CI).
//
//   node check_ffi.js <ble_ffi.json> <ble_bridge.h> <output ffi_check.cpp>
//
// Check 1 (this script) : the names in the JSON and in the header are the same set.
// Check 2 (the compiler): the output file has one static_assert per entry.
//                         If a return type or an argument type differs,
//                         the file does not compile.
'use strict'
const fs = require('fs')

const [jsonPath, headerPath, outPath] = process.argv.slice(2)
if (!jsonPath || !headerPath || !outPath) {
  console.error('usage: node check_ffi.js <ble_ffi.json> <ble_bridge.h> <output.cpp>')
  process.exit(2)
}

function fail (lines) {
  console.error('FFI check failed:')
  for (const line of lines) console.error('  ' + line)
  process.exit(1)
}

let map
try {
  map = JSON.parse(fs.readFileSync(jsonPath, 'utf8'))
} catch (err) {
  fail([`cannot read ${jsonPath}: ${err.message}`])
}
const header = fs.readFileSync(headerPath, 'utf8')

const types = map.types || {}
const callbacks = map.callbacks || {}
const functions = map.functions || {}

// ---- names declared in the header ----
// functions: BLE_API <type> <name>(
const headerFunctions = [...header.matchAll(/BLE_API\s+\w+[\s*]+(\w+)\s*\(/g)].map((m) => m[1])
// callbacks: typedef <type> (*<name>)(
const headerCallbacks = [...header.matchAll(/typedef\s+\w+[\s*]*\(\s*\*\s*(\w+)\s*\)\s*\(/g)].map((m) => m[1])

// ---- check 1: both name sets must be equal ----
const errors = []
function compareNames (what, jsonNames, headerNames) {
  for (const name of jsonNames) {
    if (!headerNames.includes(name)) errors.push(`${what} '${name}' is in ble_ffi.json but not in ble_bridge.h`)
  }
  for (const name of headerNames) {
    if (!jsonNames.includes(name)) errors.push(`${what} '${name}' is in ble_bridge.h but not in ble_ffi.json`)
  }
}
compareNames('callback', Object.keys(callbacks), headerCallbacks)
compareNames('function', Object.keys(functions), headerFunctions)

// ---- check 2: generate static_asserts for the types ----
// JSON type name -> C type. A callback name is used as it is.
function cType (name, where) {
  if (Object.prototype.hasOwnProperty.call(callbacks, name)) return name
  if (Object.prototype.hasOwnProperty.call(types, name)) return types[name]
  errors.push(`unknown type '${name}' in ${where} (add it to "types" in ble_ffi.json)`)
  return 'void'
}

// "ret(*)(arg, arg)" for one entry
function cSignature (name, entry) {
  if (typeof entry.ret !== 'string' || !Array.isArray(entry.args)) {
    errors.push(`'${name}' needs "ret" (string) and "args" (array)`)
    return 'void(*)()'
  }
  const ret = cType(entry.ret, name)
  const args = entry.args.map((arg) => cType(arg, name))
  return `${ret}(*)(${args.join(', ')})`
}

let code = ''
code += '// Generated by check_ffi.js from ble_ffi.json. Do not edit.\n'
code += '// If this file does not compile, ble_ffi.json and ble_bridge.h do not match.\n'
code += '#include "ble_bridge.h"\n#include <type_traits>\n\n'

for (const [name, entry] of Object.entries(callbacks)) {
  code += `static_assert(std::is_same<${name}, ${cSignature(name, entry)}>::value,\n`
  code += `    "ble_ffi.json: callback ${name} does not match ble_bridge.h");\n`
}
code += '\n'
for (const [name, entry] of Object.entries(functions)) {
  code += `static_assert(std::is_same<decltype(&${name}), ${cSignature(name, entry)}>::value,\n`
  code += `    "ble_ffi.json: function ${name} does not match ble_bridge.h");\n`
}

if (errors.length > 0) fail(errors)

fs.writeFileSync(outPath, code)
console.log(`FFI check: names OK (version ${map.version}, ` +
  `${Object.keys(functions).length} functions, ${Object.keys(callbacks).length} callbacks)`)
